-- =============================================================================
-- HABITASPHERE DATABASE CLEANUP & CONSTRAINTS SCRIPT
-- =============================================================================
-- This script fixes orphaned user_roles records safely and configures proper
-- cascading constraints to prevent future referential integrity issues.
-- Use this script in your PostgreSQL database tool (PgAdmin, DBeaver, psql, etc.).

-- 1. IDENTIFY ORPHANED RECORDS (For manual audit/review)
-- =============================================================================
-- Retrieve orphaned records where user_id does not exist in 'users' table
SELECT 
    ur.user_id, 
    ur.role_id 
FROM 
    user_roles ur
LEFT JOIN 
    users u ON ur.user_id = u.id
WHERE 
    u.id IS NULL;

-- Retrieve orphaned records where role_id does not exist in 'roles' table
SELECT 
    ur.user_id, 
    ur.role_id 
FROM 
    user_roles ur
LEFT JOIN 
    roles r ON ur.role_id = r.id
WHERE 
    r.id IS NULL;


-- 2. PURGE ORPHANED RECORDS SAFELY
-- =============================================================================
-- Delete user_roles entries pointing to non-existent users (e.g. user_id = 33)
DELETE FROM user_roles 
WHERE user_id NOT IN (SELECT id FROM users);

-- Delete user_roles entries pointing to non-existent roles
DELETE FROM user_roles 
WHERE role_id NOT IN (SELECT id FROM roles);


-- 3. ESTABLISH ROBUST CASCADE FOREIGN KEYS
-- =============================================================================
-- Re-create the user_roles foreign key to users with ON DELETE CASCADE.
-- This ensures that when a User is deleted, their roles mappings are purged automatically.

-- A) Drop existing constraint if it exists (standard names generated by Hibernate vary, so we check/drop)
ALTER TABLE user_roles 
    DROP CONSTRAINT IF EXISTS fk_user_roles_user,
    DROP CONSTRAINT IF EXISTS fk_user_roles_user_id,
    DROP CONSTRAINT IF EXISTS FKfhs83cf7w8o7beh85pa995f3n; -- Common hibernate default name

ALTER TABLE user_roles 
    ADD CONSTRAINT fk_user_roles_user 
    FOREIGN KEY (user_id) 
    REFERENCES users(id) 
    ON DELETE CASCADE;

-- B) Re-create the user_roles foreign key to roles with ON DELETE CASCADE.
ALTER TABLE user_roles 
    DROP CONSTRAINT IF EXISTS fk_user_roles_role,
    DROP CONSTRAINT IF EXISTS fk_user_roles_role_id,
    DROP CONSTRAINT IF EXISTS FKh8rqwki0eg567ihkdwp71b965; -- Common hibernate default name

ALTER TABLE user_roles 
    ADD CONSTRAINT fk_user_roles_role 
    FOREIGN KEY (role_id) 
    REFERENCES roles(id) 
    ON DELETE CASCADE;

-- C) Establish ON DELETE SET NULL for apartment assignment on user
-- This ensures deleting an apartment safely nullifies the user's assignment rather than failing or deleting the user.
ALTER TABLE users 
    DROP CONSTRAINT IF EXISTS fk_users_apartment,
    DROP CONSTRAINT IF EXISTS fk_users_apartment_id,
    DROP CONSTRAINT IF EXISTS FK55itppkw3i07do3h7q1am5d8d;

ALTER TABLE users 
    ADD CONSTRAINT fk_users_apartment 
    FOREIGN KEY (apartment_id) 
    REFERENCES apartments(id) 
    ON DELETE SET NULL;

-- D) Establish ON DELETE SET NULL for society assignment on user
ALTER TABLE users 
    DROP CONSTRAINT IF EXISTS fk_users_society,
    DROP CONSTRAINT IF EXISTS fk_users_society_id,
    DROP CONSTRAINT IF EXISTS FKg34r3yv8u10i9r0i99a9a0t;

ALTER TABLE users 
    ADD CONSTRAINT fk_users_society 
    FOREIGN KEY (society_id) 
    REFERENCES societies(id) 
    ON DELETE SET NULL;


-- 4. BOOTSTRAP INITIAL DATA (Roles and Default Society)
-- =============================================================================
-- Safely insert default roles if they do not exist.
-- Spring Security hasRole('ADMIN') checks for ROLE_ADMIN internally, so store
-- the ROLE_ prefix in the database.
INSERT INTO roles (name)
SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (name)
SELECT 'ROLE_SECURITY' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_SECURITY');

INSERT INTO roles (name)
SELECT 'ROLE_RESIDENT' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_RESIDENT');

INSERT INTO roles (name)
SELECT 'ROLE_SECRETARY' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_SECRETARY');

-- Older versions used ROLE_USER. Move those assignments to ROLE_RESIDENT so
-- @PreAuthorize("hasRole('RESIDENT')") works for existing resident accounts.
UPDATE user_roles
SET role_id = (SELECT id FROM roles WHERE name = 'ROLE_RESIDENT')
WHERE role_id IN (SELECT id FROM roles WHERE name = 'ROLE_USER')
  AND NOT EXISTS (
      SELECT 1
      FROM user_roles existing
      WHERE existing.user_id = user_roles.user_id
        AND existing.role_id = (SELECT id FROM roles WHERE name = 'ROLE_RESIDENT')
  );

DELETE FROM user_roles
WHERE role_id IN (SELECT id FROM roles WHERE name = 'ROLE_USER');

DELETE FROM roles
WHERE name = 'ROLE_USER';

-- Safely insert a default Society with ID = 1 for initial user registrations
INSERT INTO societies (id, name, address, city, state, country, pin_code)
SELECT 1, 'HabitaSphere Residency', '100 Green Avenue', 'Metropolis', 'NY', 'USA', '10001'
WHERE NOT EXISTS (SELECT 1 FROM societies WHERE id = 1);

-- To promote a registered user to ADMIN, register them first and then run this query:
-- INSERT INTO user_roles (user_id, role_id) 
-- VALUES (
--     (SELECT id FROM users WHERE email = 'admin@example.com'), 
--     (SELECT id FROM roles WHERE name = 'ROLE_ADMIN')
-- );
